version: '2'

services:


      ##-----------------------------------------------
      # mariadb
      ##-----------------------------------------------
      db:
        container_name: 'dev_db'
        build: ./services/mysql
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
          - "3306:3306"
        volumes:
          - ${MYSQL_DATA_PATH}:/var/lib/mysql

      ##-----------------------------------------------
      # php
      ##-----------------------------------------------
      php:
        container_name: 'dev_php'
        build: ./services/php
        volumes:
          - ${APPLICATION}:/mnt/app
          - ./services/supervisor:/etc/supervisor
        ports:
          - "9000:9000"
          - "8888:8888"

      php56:
        container_name: 'dev_php_56'
        build: ./services/php56
        volumes:
          - ${APPLICATION}:/mnt/app
        ports:
          - "9001:9000"


      php71:
        container_name: 'dev_php_71'
        build: ./services/php71
        volumes:
          - ${APPLICATION}:/mnt/app
        ports:
          - "9002:9000"



      ##-----------------------------------------------
      # nginx
      ##-----------------------------------------------
      web:
        container_name: 'dev_nginx'
        build: ./services/nginx
        ports:
          - "80:80"
          - "1935:1935"
        depends_on:
          - php
        volumes_from:
          - php
        volumes:
          - ${NGINX_VOLUME_CONFIG_PATH}:/etc/nginx/conf.d
        dns: 8.8.8.8
       
        # privileged: true


      elasticsearch:
        container_name: 'dev_elasticsearch'
        image: elasticsearch
        volumes:
          - ./services/elasticsearch/data:/usr/share/elasticsearch/data
          - ./services/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        ports:
          - "9200:9200"
          - "9300:9300"

      # tomcat:
      #   container_name: 'local_tomcat'
      #   image: 'tomcat:latest'
      #   volumes:
      #     - ${JAVA_APPLICATION}:/usr/local/tomcat/webapps/web
      #   ports:
      #     - "8888:8080"
      #   tty: true


      ##-----------------------------------------------
      # node
      ##-----------------------------------------------
      # node:
      #   container_name: 'local_node'
      #   build: ./services/node
      #   ports:
      #     - "3000:3000"
      #     - "3001:3001"
      #     - "3002:3002"
      #     - "3003:3003"
      #     - "3004:3004"
      #   volumes:
      #     - ${NODE_APPLICATION}:/var/www
      #   tty: true

      # redis:
      #   container_name: 'local_redis'
